formsProject/urls.py
from django.contrib import admin
from django.urls import path
from forms_App import views
from django.conf.urls import include


urlpatterns = [
    path('', include('forms_App.urls')),
    path('admin/', admin.site.urls),
]

forms_App/urls.py
from django.urls import path
from forms_App import views


urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.Login, name='login')
]

forms_App/models.py
from django.db import models


# Create your models here.


class UserLogs(models.Model):
    username = models.CharField(max_length=40)
    email = models.EmailField()
    phone = models.IntegerField()
    password = models.CharField(max_length=40)

    def __str__(self):
        return self.username

forms_App/forms.py
from django import forms


class Register(forms.Form):
    username = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=50, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    re_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class LOGIN(forms.Form):
    username = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

forms_App/views.py
from django.shortcuts import render
# from forms_App import forms
from . import forms
from forms_App.models import UserLogs

# Create your views here.

# Landing Page
def index(request):
    return render(request, 'forms_App/index.html', {})


# Signup Page
def signup(request):
    form = forms.Register()

    if request.method == 'POST':
        user_form = forms.Register(request.POST)
        if user_form.is_valid():
            print(user_form.cleaned_data['username'])

    return render(request, 'forms_App/signup.html', {'form': form})


# Login Page
def Login(request):
    formLogin = forms.LOGIN()

    if request.method == 'POST':
        user_form = forms.LOGIN(request.POST)

        if user_form.is_valid():
            print(user_form.cleaned_data['username'])
    else:
        print("no")
    return render(request, 'forms_App/Login.html', {'form': formLogin})

templates/forms_App/Login.html
{% extends 'forms_App/base.html' %}
{% block app_styles %}
    body{
        background-color:black;
    }
    .container{
        margin-top:5rem;
        color:white;
        padding-top:0rem;
        padding-bottom:0rem;
<!--            margin:auto;-->
        width:50%;
<!--            border:2px solid white;-->
        border-width: 3px;
        border-style: solid;
        border-image:
        linear-gradient(
          to bottom,
          red,
          rgba(0, 0, 0, 0)
        ) 1 100%;
    }
    .container form{
<!--            margin:auto;-->
        width:50%;
        padding: 0rem 4rem 4rem 4rem;
    }
{% endblock %}

{% block sub_content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <h2><center>Sign in</center></h2>

  <div class="form-group">
    <label for="id_username">Username</label>
<!--    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
      {{form.username}}
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="id_password">Password</label>
<!--    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
      {{form.password}}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

templates/forms_App/_navbar.html
<style>
    .nav-item{
        color:white;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: black">
  <a class="navbar-brand" href="/">DJANGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/signup/">Sign up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/signin/">Sign in</a>
      </li>
    </ul>
  </div>
</nav>














<!--  <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown link-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->







<!-- <ul class="nav nav-tabs">-->
<!--      <li class="nav-item">-->
<!--          <a class="nav-link" href="/">DJANGO</a>-->
<!--      </li>-->
<!--      <li>-->
<!--          <a class="nav-link" href="/signup/">sign up</a>-->
<!--      </li>-->
<!--      <li>-->
<!--          <a class="nav-link" href="/signin/">sign in</a>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->
<!--      </li>-->
<!--&lt;!&ndash;      <li class="nav-item">&ndash;&gt;-->
<!--&lt;!&ndash;        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>&ndash;&gt;-->
<!--&lt;!&ndash;      </li>&ndash;&gt;-->
<!-- </ul>-->

templates/forms_App/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>
    <style>
        {% block app_styles %}
            body{
                background-color:black;
            }
        {% endblock %}
    </style>
</head>
<body>
    {% include 'forms_App/_navbar.html' %}
    {% block content %}
        {% block sub_content %}
        {% endblock %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/forms_App/index.html
{% extends 'forms_App/base.html' %}
    {% block title %}DJANGO{% endblock %}

templates/forms_App/signup.html
{% extends 'forms_App/base.html' %}
    {% block title %}
        Sign up
    {% endblock %}
    {% block app_styles %}
            body{
        background-color:black;
    }
    .container{
        margin-top:5rem;
        color:white;
        padding-top:0rem;
        padding-bottom:0rem;
<!--            margin:auto;-->
        width:50%;
<!--            border:2px solid white;-->
        border-width: 3px;
        border-style: solid;
        border-image:
        linear-gradient(
          to bottom,
          red,
          rgba(0, 0, 0, 0)
        ) 1 100%;
    }
    .container form{
<!--            margin:auto;-->
        width:50%;
        padding: 0rem 4rem 4rem 4rem;
    }
    {% endblock %}
    {% include 'forms_App/_navbar.html' %}
    {% block sub_content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <h2><center>Sign up</center></h2>
              <div class="form-group">
                <label for="id_username">Username</label>
            <!--    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
                  {{form.username}}
              </div>
            <div class="form-group">
                <label for="id_email">Email</label>
            <!--    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
                  {{form.email}}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
            <div class="form-group">
                <label for="id_phone">Phone</label>
            <!--    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
                  {{form.phone}}
              </div>
              <div class="form-group">
                <label for="id_password">Password</label>
            <!--    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
                  {{form.password}}
              </div>
            <div class="form-group">
                <label for="id_re_password">Re-Enter your Password</label>
            <!--    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
                  {{form.re_password}}
              </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    {% endblock %}





<!--<div class="container">-->
<!--&lt;!&ndash;        <p>"Hello"</p>&ndash;&gt;-->
<!--        <div class="container">-->
<!--        <form method="post">-->
<!--            {% csrf_token %}-->
<!--            {{ form.username }}-->
<!--            <input type="submit" value="submit" class="btn btn btn-primary">-->
<!--        </form></div>-->
<!--    </div>-->